/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.openjfx.javafxplugin") version ("0.0.13")
    id("com.stulsoft.photo.tools.java-application-conventions")
    id("extra-java-module-info")
}

dependencies {
    implementation("org.apache.commons:commons-imaging:1.0-alpha3")
    implementation(project(":slib"))
}

application {
    mainModule.set("com.stulsoft.photo.tools")
    mainClass.set("com.stulsoft.photo.tools.App")
}

javafx {
    version = "19"
    modules("javafx.controls", "javafx.fxml")
}

tasks.jar{
    manifest{
        attributes(
            "Implementation-Version" to archiveVersion
        )
    }
}

extraJavaModuleInfo {
    automaticModule("slib-${version}.jar", "com.stulsoft.photo.slib")
    automaticModule("slib-${version}.jar", "com.stulsoft.photo.slib.emptydir")
}
